# -----------  Agents  -----------
[[agents]]
  id = "test_agent1"
  name = "Agent 1"
  public_address = "HcSCjKW9aqU57act6gCKdeTTSRbj89ejuHq534nmuDeNjhr7F783qV7OwH4wcca"
  keystore_file = "./agent1.keystore"

# -----------  DNAs  -----------

[[dnas]]
  id = "basic_chat_dna"
  file = "./dna/basic-chat.dna.json"
  hash = "Qma5ncMshmqxrmAWTVg5Yc65rsvv52TFj7PZpyhC8r6xd1"


# -----------  Instances  -----------

[[instances]]
  id = "basic-chat"
  dna = "basic_chat_dna"
  agent = "test_agent1"
[instances.storage]
  type = "memory"

# -----------  Interfaces  -----------

[[interfaces]]
  id = "websocket_interface"
  admin = true
[interfaces.driver]
  type = "websocket"
  port = 3401
[[interfaces.instances]]
  id = "basic-chat"
# -----------  Networking  -----------

[network]
  type = "sim2h"
  sim2h_url = 'ws://localhost:9000'
